service: blog
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    NODE_ENV: ${opt:stage}
    Table_NAME: HowzitHoozle-free-db
  httpApi:
    authorizers:
      cognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_8XqxLcWFP
        audience:
          - 2cbsuopm63g2gopfvjl35vt6mi
    cors: true

custom:
  tableName: HowzitHoozle-free-db

functions:
  getAllEntriesInfinite:
    handler: dist/getBlogPostsInfinite/getHandler.handler
    events:
      - httpApi:
          path: /blog/getAllInfinite/{currentPageId}
          method: GET
  updateEntry:
    handler: dist/updateBlogPost/updateHandler.handler
    events:
      - httpApi:
          path: /blog/update/{entityId}
          method: PUT
          authorizer:
            name: cognitoAuthorizer
  createArticle:
    handler: dist/createArticle/createHandler.handler
    events:
      - httpApi:
          path: /blog/create
          method: POST
          authorizer:
            name: cognitoAuthorizer
#  deleteEntry:
#    handler: dist/deleteBlogPost/deleteHandler.handler
#    events:
#      - httpApi:
#          path: /blog/delete/{id}
#          method: DELETE
#          authorizer:
#            name: cognitoAuthorizer
